server:
  port: 8080

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:    name: ApiGateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
      - id: ArticleService
        uri: lb://ARTICLESERVICE
        predicates:
        - Path=/article_service/**
      - id: CustomerService
        uri: lb://CUSTOMERSERVICE
        predicates:
        - Path=/customer_service/**
      - id: OrderService
        uri: lb://ORDERSERVICE
        predicates:
        - Path=/order_service/**